spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import:
    - optional:file:.env[.properties]
#    - configserver:http://localhost:8888

  cloud:
    config:
      uri: http://localhost:8888
      name: application-dev.yml
      label: main



security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9898



